# Robolab ModBrick

modbrick-objs := modbrick_leds.o modbrick_ports_out.o \
                    modbrick_ports_in.o modbrick_spi.o \
                    modbrick_supply.o modbrick_board.o
obj-$(CONFIG_MODBRICK)	+= modbrick.o


